// <auto-generated />
using System;
using FlowPilot.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Migrators.MSSQL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260428115027_am_m21")]
    partial class am_m21
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentAvailabilityProposedWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentAvailabilityProposedWindowStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKTempAppointmentParticipantsPkId")
                        .HasColumnType("int");

                    b.Property<int>("FKTempAppointmentsPKId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OnDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TimeTo")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FKTempAppointmentParticipantsPkId");

                    b.HasIndex("FKTempAppointmentsPKId");

                    b.ToTable("TempAppointmentAvailabilityProposedWindow", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentAvailabilityWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKTempAppointmentsPKId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("OnDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("TimeFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("TimeTo")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("FKTempAppointmentsPKId");

                    b.ToTable("TempAppointmentAvailabilityWindow", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentParticipants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentParticipantResponseStatus")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentParticipantRole")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("ApproveForDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ApproveTimeFrom")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ApproveTimeTo")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeclinedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DeclinedReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FKApplicationUserPKId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKTempAppointmentsPKId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("MeetingParticipantPresenceStatus")
                        .HasColumnType("int");

                    b.Property<string>("MeetingUrlIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UrlIdentifier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FKTempAppointmentsPKId");

                    b.ToTable("TempAppointmentParticipants", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("ApprovalRule")
                        .HasColumnType("int");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FKCancelledByApplicationUserPKId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FKTempAppointmentPkId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LocationType")
                        .HasColumnType("int");

                    b.Property<int>("MultipleParticipantPerSlot")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FKTempAppointmentPkId");

                    b.ToTable("TempAppointments", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Email.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bcc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSentMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSmtpUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailToUserIds")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailType")
                        .HasColumnType("int");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTestModeEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("ReplyTo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplyToName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SendGridMessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmailLog", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Email.EmailTemplates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsShared")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TemplateUsedFor")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageFieldOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKFormPageFieldPKId")
                        .HasColumnType("int");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FKFormPageFieldPKId");

                    b.ToTable("FormPageFieldOptions", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FKFormPageFieldTabId")
                        .HasColumnType("int");

                    b.Property<int>("FKFormPagePKId")
                        .HasColumnType("int");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("FieldKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FormPageFieldType")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdditionalCommentAllowed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FKFormPageFieldTabId");

                    b.HasIndex("FKFormPagePKId");

                    b.ToTable("FormPageFields", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageTabs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKFormPagePKId")
                        .HasColumnType("int");

                    b.Property<int?>("FKFormPageTabPKId")
                        .HasColumnType("int");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FKFormPagePKId");

                    b.HasIndex("FKFormPageTabPKId");

                    b.ToTable("FormPageTabs", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKFormStructurePKId")
                        .HasColumnType("int");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("IntroText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FKFormStructurePKId");

                    b.ToTable("FormPages", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormStructures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FormStatus")
                        .HasColumnType("int");

                    b.Property<string>("IntroductionText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FormStructures", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.LookUp.LookUpCodeValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FKLookUpCodePKId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LookUpValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FKLookUpCodePKId");

                    b.ToTable("LookUpCodeValues", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.LookUp.LookUpCodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("LookUpCodeType")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("LookUpCodes", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Setting.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("OriginalValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SettingType")
                        .HasColumnType("int");

                    b.Property<string>("SettingValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Settings", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentAvailabilityProposedWindow", b =>
                {
                    b.HasOne("FlowPilot.Domain.Appointment.TempAppointmentParticipants", "TempAppointmentParticipant")
                        .WithMany()
                        .HasForeignKey("FKTempAppointmentParticipantsPkId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlowPilot.Domain.Appointment.TempAppointments", "TempAppointment")
                        .WithMany("TempAppointmentAvailabilityProposedWindows")
                        .HasForeignKey("FKTempAppointmentsPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TempAppointment");

                    b.Navigation("TempAppointmentParticipant");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentAvailabilityWindow", b =>
                {
                    b.HasOne("FlowPilot.Domain.Appointment.TempAppointments", "TempAppointment")
                        .WithMany("TempAppointmentAvailabilityWindows")
                        .HasForeignKey("FKTempAppointmentsPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TempAppointment");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentParticipants", b =>
                {
                    b.HasOne("FlowPilot.Domain.Appointment.TempAppointments", "TempAppointment")
                        .WithMany("TempAppointmentParticipants")
                        .HasForeignKey("FKTempAppointmentsPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TempAppointment");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointments", b =>
                {
                    b.HasOne("FlowPilot.Domain.Appointment.TempAppointments", "TempAppointment")
                        .WithMany()
                        .HasForeignKey("FKTempAppointmentPkId");

                    b.Navigation("TempAppointment");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageFieldOptions", b =>
                {
                    b.HasOne("FlowPilot.Domain.FormDesigner.FormPageFields", "FormPageField")
                        .WithMany("FormPageFieldOptions")
                        .HasForeignKey("FKFormPageFieldPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormPageField");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageFields", b =>
                {
                    b.HasOne("FlowPilot.Domain.FormDesigner.FormPageTabs", "FormPageTab")
                        .WithMany("Fields")
                        .HasForeignKey("FKFormPageFieldTabId");

                    b.HasOne("FlowPilot.Domain.FormDesigner.FormPages", "FormPage")
                        .WithMany("Fields")
                        .HasForeignKey("FKFormPagePKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormPage");

                    b.Navigation("FormPageTab");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageTabs", b =>
                {
                    b.HasOne("FlowPilot.Domain.FormDesigner.FormPages", "FormPage")
                        .WithMany("Tabs")
                        .HasForeignKey("FKFormPagePKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlowPilot.Domain.FormDesigner.FormPageTabs", "ParentTab")
                        .WithMany("ChildTabs")
                        .HasForeignKey("FKFormPageTabPKId");

                    b.Navigation("FormPage");

                    b.Navigation("ParentTab");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPages", b =>
                {
                    b.HasOne("FlowPilot.Domain.FormDesigner.FormStructures", "FormStructure")
                        .WithMany("FormPages")
                        .HasForeignKey("FKFormStructurePKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormStructure");
                });

            modelBuilder.Entity("FlowPilot.Domain.LookUp.LookUpCodeValues", b =>
                {
                    b.HasOne("FlowPilot.Domain.LookUp.LookUpCodes", "LookUpCode")
                        .WithMany("LookUpCodeValues")
                        .HasForeignKey("FKLookUpCodePKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LookUpCode");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointments", b =>
                {
                    b.Navigation("TempAppointmentAvailabilityProposedWindows");

                    b.Navigation("TempAppointmentAvailabilityWindows");

                    b.Navigation("TempAppointmentParticipants");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageFields", b =>
                {
                    b.Navigation("FormPageFieldOptions");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageTabs", b =>
                {
                    b.Navigation("ChildTabs");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPages", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Tabs");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormStructures", b =>
                {
                    b.Navigation("FormPages");
                });

            modelBuilder.Entity("FlowPilot.Domain.LookUp.LookUpCodes", b =>
                {
                    b.Navigation("LookUpCodeValues");
                });
#pragma warning restore 612, 618
        }
    }
}
