<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Migrators.PostgreSQL</RootNamespace>
    <AssemblyName>Migrators.PostgreSQL</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\NexusDb\**" />
    <EmbeddedResource Remove="Migrations\NexusDb\**" />
    <None Remove="Migrations\NexusDb\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.3" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="Roslynator.Analyzers" Version="4.15.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\AuditingDb\" />
  </ItemGroup>

</Project>
