<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Migrators.PostgreSQL</RootNamespace>
    <AssemblyName>Migrators.PostgreSQL</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Update="Roslynator.Analyzers" Version="4.15.0" />
  </ItemGroup>

</Project>
