// <auto-generated />
using System;
using System.Collections.Generic;
using FlowPilot.Infrastructure.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Migrators.PostgreSQL.Migrations.ApplicationDb
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260817082152_CRM_OfferingGuidAndOptionalAssignee")]
    partial class CRM_OfferingGuidAndOptionalAssignee
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentAvailabilityProposedWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentAvailabilityProposedWindowStatus")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKTempAppointmentParticipantsPkId")
                        .HasColumnType("integer");

                    b.Property<int>("FKTempAppointmentsPKId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TimeFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TimeTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FKTempAppointmentParticipantsPkId");

                    b.HasIndex("FKTempAppointmentsPKId")
                        .HasDatabaseName("IX_TempAppointmentAvailabilityProposedWindow_FKTempAppointmen~1");

                    b.ToTable("TempAppointmentAvailabilityProposedWindow", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentAvailabilityWindow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKTempAppointmentsPKId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("TimeFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("TimeTo")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FKTempAppointmentsPKId");

                    b.ToTable("TempAppointmentAvailabilityWindow", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentParticipants", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentParticipantResponseStatus")
                        .HasColumnType("integer");

                    b.Property<int>("AppointmentParticipantRole")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("ApproveForDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ApproveTimeFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ApproveTimeTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeclinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeclinedReason")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FKApplicationUserPKId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKTempAppointmentsPKId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MeetingParticipantPresenceStatus")
                        .HasColumnType("integer");

                    b.Property<string>("MeetingUrlIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UrlIdentifier")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FKTempAppointmentsPKId");

                    b.ToTable("TempAppointmentParticipants", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointments", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentStatus")
                        .HasColumnType("integer");

                    b.Property<int>("ApprovalRule")
                        .HasColumnType("integer");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("FKCancelledByApplicationUserPKId")
                        .HasColumnType("text");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("FKTempAppointmentPkId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LocationType")
                        .HasColumnType("integer");

                    b.Property<int>("MultipleParticipantPerSlot")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FKTempAppointmentPkId");

                    b.ToTable("TempAppointments", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.GpsLogs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKLeadVisitPKId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("LoggedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FKLeadVisitPKId");

                    b.ToTable("GpsLogs", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.GpsVerifications", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DistanceMeters")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKGpsLogPKId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FKGpsLogPKId")
                        .IsUnique();

                    b.ToTable("GpsVerifications", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadActivities", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<TimeSpan?>("ActivityTime")
                        .HasColumnType("interval");

                    b.Property<int>("ActivityType")
                        .HasColumnType("integer");

                    b.Property<string>("AttachmentUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKLeadPKId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("NextFollowUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Outcome")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FKLeadPKId");

                    b.ToTable("LeadActivities", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadAssignmentHistories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AssignedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("AssignedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKLeadPKId")
                        .HasColumnType("integer");

                    b.Property<string>("FromUserId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ToUserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FKLeadPKId");

                    b.ToTable("LeadAssignmentHistories", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadContacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternatePhone")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Designation")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKLeadPKId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("WhatsApp")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FKLeadPKId");

                    b.ToTable("LeadContacts", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadFollowUps", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKLeadPKId")
                        .HasColumnType("integer");

                    b.Property<int>("FollowUpStatus")
                        .HasColumnType("integer");

                    b.Property<int>("FollowUpType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("NextFollowUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReminderNote")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FKLeadPKId");

                    b.ToTable("LeadFollowUps", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadImages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKLeadVisitPKId")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FKLeadVisitPKId");

                    b.ToTable("LeadImages", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadStatusHistories", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangedByUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ChangedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("FKFromStatusId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKLeadPKId")
                        .HasColumnType("integer");

                    b.Property<int>("FKToStatusId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FKFromStatusId");

                    b.HasIndex("FKLeadPKId");

                    b.HasIndex("FKToStatusId");

                    b.ToTable("LeadStatusHistories", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadVisits", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKLeadPKId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("VisitTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FKLeadPKId");

                    b.ToTable("LeadVisits", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.Leads", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasColumnType("text");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BusinessType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("CompanySize")
                        .HasColumnType("text");

                    b.Property<string>("Competitors")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ConvertedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentPOS")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("ExpectedClosingDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("ExpectedMonthlyBilling")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExpectedRevenue")
                        .HasColumnType("numeric");

                    b.Property<string>("FKAssignedToUserId")
                        .HasColumnType("text");

                    b.Property<int?>("FKConvertedCustomerId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKLeadSourceId")
                        .HasColumnType("integer");

                    b.Property<int>("FKLeadStatusId")
                        .HasColumnType("integer");

                    b.Property<int?>("FKOfferingId")
                        .HasColumnType("integer");

                    b.Property<string>("FullAddress")
                        .HasColumnType("text");

                    b.Property<string>("GoogleMapsLink")
                        .HasColumnType("text");

                    b.Property<string>("GstNumber")
                        .HasColumnType("text");

                    b.Property<int>("InterestLevel")
                        .HasColumnType("integer");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastActivityDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset?>("NextFollowUpDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("NumberOfOutlets")
                        .HasColumnType("integer");

                    b.Property<string>("PainPoints")
                        .HasColumnType("text");

                    b.Property<string>("Pan")
                        .HasColumnType("text");

                    b.Property<string>("Pincode")
                        .HasColumnType("text");

                    b.Property<string>("PlaceId")
                        .HasColumnType("text");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<string>("Requirements")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Website")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FKLeadSourceId");

                    b.HasIndex("FKLeadStatusId");

                    b.HasIndex("FKOfferingId");

                    b.ToTable("Leads", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.Offerings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal?>("ExpectedValueFrom")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("ExpectedValueTo")
                        .HasColumnType("numeric");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("FKOwnerUserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("UniqueId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UniqueId")
                        .IsUnique();

                    b.ToTable("Offerings", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.Tasks", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Bucket")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Type")
                        .HasColumnType("integer");

                    b.Property<Guid>("Uuid")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("When")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Uuid")
                        .IsUnique();

                    b.ToTable("Tasks", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Common.EntityNotes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EntityNoteType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKEntityPKId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NoteText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EntityNotes", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Email.EmailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<List<string>>("Bcc")
                        .HasColumnType("text[]");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Cc")
                        .HasColumnType("text[]");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("EmailBccUserIds")
                        .HasColumnType("uuid[]");

                    b.PrimitiveCollection<List<Guid>>("EmailCcUserIds")
                        .HasColumnType("uuid[]");

                    b.Property<string>("EmailSentMessage")
                        .HasColumnType("text");

                    b.Property<string>("EmailSmtpUsed")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<Guid>>("EmailToUserIds")
                        .HasColumnType("uuid[]");

                    b.Property<int>("EmailType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEmailSent")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTestModeEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplyTo")
                        .HasColumnType("text");

                    b.Property<string>("ReplyToName")
                        .HasColumnType("text");

                    b.Property<string>("SendGridMessageId")
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("To")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("EmailLog", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Email.EmailTemplates", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("EmailBody")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmailSubject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TemplateUsedFor")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("EmailTemplates", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageFieldOptions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKFormPageFieldPKId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FKFormPageFieldPKId");

                    b.ToTable("FormPageFieldOptions", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageFields", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int?>("FKFormPageFieldTabId")
                        .HasColumnType("integer");

                    b.Property<int>("FKFormPagePKId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FieldKey")
                        .HasColumnType("uuid");

                    b.Property<int>("FormPageFieldType")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAdditionalCommentAllowed")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FKFormPageFieldTabId");

                    b.HasIndex("FKFormPagePKId");

                    b.ToTable("FormPageFields", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageTabs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKFormPagePKId")
                        .HasColumnType("integer");

                    b.Property<int?>("FKFormPageTabPKId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FKFormPagePKId");

                    b.HasIndex("FKFormPageTabPKId");

                    b.ToTable("FormPageTabs", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPages", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKFormStructurePKId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("IntroText")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FKFormStructurePKId");

                    b.ToTable("FormPages", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormStructures", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FormStatus")
                        .HasColumnType("integer");

                    b.Property<string>("IntroductionText")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("FormStructures", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.LookUp.LookUpCodeValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("FKLookUpCodePKId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LookUpValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FKLookUpCodePKId");

                    b.ToTable("LookUpCodeValues", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.LookUp.LookUpCodes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LookUpCodeType")
                        .HasColumnType("integer");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LookUpCodes", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Setting.Settings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DeletedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("FKDeletedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FKLastModifiedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastModifiedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SettingType")
                        .HasColumnType("integer");

                    b.Property<string>("SettingValues")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Settings", "dbo");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentAvailabilityProposedWindow", b =>
                {
                    b.HasOne("FlowPilot.Domain.Appointment.TempAppointmentParticipants", "TempAppointmentParticipant")
                        .WithMany()
                        .HasForeignKey("FKTempAppointmentParticipantsPkId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlowPilot.Domain.Appointment.TempAppointments", "TempAppointment")
                        .WithMany("TempAppointmentAvailabilityProposedWindows")
                        .HasForeignKey("FKTempAppointmentsPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TempAppointment");

                    b.Navigation("TempAppointmentParticipant");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentAvailabilityWindow", b =>
                {
                    b.HasOne("FlowPilot.Domain.Appointment.TempAppointments", "TempAppointment")
                        .WithMany("TempAppointmentAvailabilityWindows")
                        .HasForeignKey("FKTempAppointmentsPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TempAppointment");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointmentParticipants", b =>
                {
                    b.HasOne("FlowPilot.Domain.Appointment.TempAppointments", "TempAppointment")
                        .WithMany("TempAppointmentParticipants")
                        .HasForeignKey("FKTempAppointmentsPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("TempAppointment");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointments", b =>
                {
                    b.HasOne("FlowPilot.Domain.Appointment.TempAppointments", "TempAppointment")
                        .WithMany()
                        .HasForeignKey("FKTempAppointmentPkId");

                    b.Navigation("TempAppointment");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.GpsLogs", b =>
                {
                    b.HasOne("FlowPilot.Domain.CRM.LeadVisits", "Visit")
                        .WithMany("GpsLogs")
                        .HasForeignKey("FKLeadVisitPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.GpsVerifications", b =>
                {
                    b.HasOne("FlowPilot.Domain.CRM.GpsLogs", "GpsLog")
                        .WithOne("Verification")
                        .HasForeignKey("FlowPilot.Domain.CRM.GpsVerifications", "FKGpsLogPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GpsLog");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadActivities", b =>
                {
                    b.HasOne("FlowPilot.Domain.CRM.Leads", "Lead")
                        .WithMany("LeadActivities")
                        .HasForeignKey("FKLeadPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadAssignmentHistories", b =>
                {
                    b.HasOne("FlowPilot.Domain.CRM.Leads", "Lead")
                        .WithMany("LeadAssignmentHistories")
                        .HasForeignKey("FKLeadPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadContacts", b =>
                {
                    b.HasOne("FlowPilot.Domain.CRM.Leads", "Lead")
                        .WithMany("LeadContacts")
                        .HasForeignKey("FKLeadPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadFollowUps", b =>
                {
                    b.HasOne("FlowPilot.Domain.CRM.Leads", "Lead")
                        .WithMany("LeadFollowUps")
                        .HasForeignKey("FKLeadPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadImages", b =>
                {
                    b.HasOne("FlowPilot.Domain.CRM.LeadVisits", "Visit")
                        .WithMany("Images")
                        .HasForeignKey("FKLeadVisitPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Visit");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadStatusHistories", b =>
                {
                    b.HasOne("FlowPilot.Domain.LookUp.LookUpCodeValues", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FKFromStatusId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("FlowPilot.Domain.CRM.Leads", "Lead")
                        .WithMany("LeadStatusHistories")
                        .HasForeignKey("FKLeadPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlowPilot.Domain.LookUp.LookUpCodeValues", "ToStatus")
                        .WithMany()
                        .HasForeignKey("FKToStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FromStatus");

                    b.Navigation("Lead");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadVisits", b =>
                {
                    b.HasOne("FlowPilot.Domain.CRM.Leads", "Lead")
                        .WithMany("LeadVisits")
                        .HasForeignKey("FKLeadPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lead");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.Leads", b =>
                {
                    b.HasOne("FlowPilot.Domain.LookUp.LookUpCodeValues", "LeadSource")
                        .WithMany()
                        .HasForeignKey("FKLeadSourceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlowPilot.Domain.LookUp.LookUpCodeValues", "LeadStatus")
                        .WithMany()
                        .HasForeignKey("FKLeadStatusId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlowPilot.Domain.CRM.Offerings", "Offering")
                        .WithMany("Leads")
                        .HasForeignKey("FKOfferingId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("LeadSource");

                    b.Navigation("LeadStatus");

                    b.Navigation("Offering");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageFieldOptions", b =>
                {
                    b.HasOne("FlowPilot.Domain.FormDesigner.FormPageFields", "FormPageField")
                        .WithMany("FormPageFieldOptions")
                        .HasForeignKey("FKFormPageFieldPKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormPageField");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageFields", b =>
                {
                    b.HasOne("FlowPilot.Domain.FormDesigner.FormPageTabs", "FormPageTab")
                        .WithMany("Fields")
                        .HasForeignKey("FKFormPageFieldTabId");

                    b.HasOne("FlowPilot.Domain.FormDesigner.FormPages", "FormPage")
                        .WithMany("Fields")
                        .HasForeignKey("FKFormPagePKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormPage");

                    b.Navigation("FormPageTab");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageTabs", b =>
                {
                    b.HasOne("FlowPilot.Domain.FormDesigner.FormPages", "FormPage")
                        .WithMany("Tabs")
                        .HasForeignKey("FKFormPagePKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("FlowPilot.Domain.FormDesigner.FormPageTabs", "ParentTab")
                        .WithMany("ChildTabs")
                        .HasForeignKey("FKFormPageTabPKId");

                    b.Navigation("FormPage");

                    b.Navigation("ParentTab");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPages", b =>
                {
                    b.HasOne("FlowPilot.Domain.FormDesigner.FormStructures", "FormStructure")
                        .WithMany("FormPages")
                        .HasForeignKey("FKFormStructurePKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FormStructure");
                });

            modelBuilder.Entity("FlowPilot.Domain.LookUp.LookUpCodeValues", b =>
                {
                    b.HasOne("FlowPilot.Domain.LookUp.LookUpCodes", "LookUpCode")
                        .WithMany("LookUpCodeValues")
                        .HasForeignKey("FKLookUpCodePKId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("LookUpCode");
                });

            modelBuilder.Entity("FlowPilot.Domain.Appointment.TempAppointments", b =>
                {
                    b.Navigation("TempAppointmentAvailabilityProposedWindows");

                    b.Navigation("TempAppointmentAvailabilityWindows");

                    b.Navigation("TempAppointmentParticipants");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.GpsLogs", b =>
                {
                    b.Navigation("Verification");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.LeadVisits", b =>
                {
                    b.Navigation("GpsLogs");

                    b.Navigation("Images");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.Leads", b =>
                {
                    b.Navigation("LeadActivities");

                    b.Navigation("LeadAssignmentHistories");

                    b.Navigation("LeadContacts");

                    b.Navigation("LeadFollowUps");

                    b.Navigation("LeadStatusHistories");

                    b.Navigation("LeadVisits");
                });

            modelBuilder.Entity("FlowPilot.Domain.CRM.Offerings", b =>
                {
                    b.Navigation("Leads");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageFields", b =>
                {
                    b.Navigation("FormPageFieldOptions");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPageTabs", b =>
                {
                    b.Navigation("ChildTabs");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormPages", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("Tabs");
                });

            modelBuilder.Entity("FlowPilot.Domain.FormDesigner.FormStructures", b =>
                {
                    b.Navigation("FormPages");
                });

            modelBuilder.Entity("FlowPilot.Domain.LookUp.LookUpCodes", b =>
                {
                    b.Navigation("LookUpCodeValues");
                });
#pragma warning restore 612, 618
        }
    }
}
