<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <NoWarn>RCS1021;IDE0161;RCS1205</NoWarn>
    <RootNamespace>Migrators.MSSQL</RootNamespace>
    <AssemblyName>Migrators.MSSQL</AssemblyName>
  </PropertyGroup>  

  <ItemGroup>
    <ProjectReference Include="..\..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>  

  <ItemGroup>
    <Folder Include="Migrations\" />
    <Folder Include="Migrations\NexusDb\" />
  </ItemGroup>  

  <ItemGroup>
    <PackageReference Include="JWT" Version="11.0.0" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
  </ItemGroup>  

  <ItemGroup>
    <PackageReference Update="Roslynator.Analyzers" Version="4.15.0" />
  </ItemGroup>

</Project>
