<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>FlowPilot.Infrastructure</RootNamespace>
    <AssemblyName>FlowPilot.Infrastructure</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Core\Application\Application.csproj" />
    <ProjectReference Include="..\Core\Domain\Domain.csproj" />
    <ProjectReference Include="..\Core\Shared\Shared.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Asp.Versioning.Mvc" Version="10.0.0" />
    <PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="10.0.0" />
    <PackageReference Include="Elastic.Serilog.Sinks" Version="9.0.0" />
    <PackageReference Include="Figgle.Fonts" Version="0.6.6" />
    <PackageReference Include="Hangfire" Version="1.8.23" />
    <PackageReference Include="Hangfire.Console" Version="1.4.3" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.22.1" />
    <PackageReference Include="Mapster.Core" Version="10.0.7" />
    <PackageReference Include="Mapster.DependencyInjection" Version="10.0.7" />
    <!--<PackageReference Include="Hangfire.Console.Extensions" Version="2.0.0" />-->
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="JWT" Version="11.0.0" />
    <PackageReference Include="NSwag.AspNetCore" Version="14.7.1" />
    <PackageReference Include="Otp.NET" Version="1.4.1" />
    <PackageReference Include="QRCoder" Version="1.8.0" />
    <PackageReference Include="Resend" Version="0.5.0" />
    <PackageReference Include="RestSharp" Version="114.0.0" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="Stripe.net" Version="51.1.0" />
    <PackageReference Include="ZymLabs.NSwag.FluentValidation.AspNetCore" Version="0.7.1" />
    <PackageReference Include="Serilog.Exceptions" Version="8.4.0" />
    <PackageReference Include="Serilog.Enrichers.Process" Version="3.0.0" />
    <PackageReference Include="Serilog.Enrichers.Thread" Version="4.0.0" />
    <PackageReference Include="Serilog.Expressions" Version="5.0.0" />
    <PackageReference Include="Serilog.Enrichers.Environment" Version="3.0.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="10.0.0" />
    <PackageReference Include="Serilog.Formatting.Compact" Version="3.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.MSSqlServer" Version="9.0.3" />
    <PackageReference Include="Serilog.Sinks.Seq" Version="9.0.0" />
    <PackageReference Include="Figgle" Version="0.6.6" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Nexus\Setting\DbModels\" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Roslynator.Analyzers" Version="4.15.0" />
  </ItemGroup>
</Project>
